name: 'Update Package Version'
description: 'An GitHub Action to update node package version.'
author: 'yosemiteyss'

branding:
  icon: 'arrow-up-circle'
  color: 'gray-dark'

inputs:
  release_tag:
    description: 'Release tag, format must be vX.X.X'
    required: true
    default: 'v1.0.0'
  commit_lock_file:
    description: 'Whether to commit package-lock.json or not'
    required: false
    default: 'true'
  commit_user_email:
    description: 'Email address for git commit'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  commit_user_name:
    description: 'Username for git commit'
    required: false
    default: 'github-actions[bot]'
  commit_message:
    description: 'Commit message, followed by version'
    required: false
    default: 'ci: updated package version'
  commit_tag_prefix:
    description: 'Commit tag prefix, followed by version'
    required: false
    default: 'release_'

outputs:
  updated_version:
    description: 'The package version after update'

runs:
  using: node20
  main: dist/index.js
