name: 'Update Package Version'
description: 'An GitHub Action to update node package version.'
author: 'yosemiteyss'

branding:
  icon: 'arrow-up-circle'
  color: 'gray-dark'

inputs:
  runtime:
    description: 'Specify the runtime'
    required: true
    type: choice
    options:
      - node
      - dart
      - flutter
  release_tag:
    description: 'Release tag, format must be vX.X.X'
    required: true
  commit_user_email:
    description: 'Email address for git commit'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  commit_user_name:
    description: 'Username for git commit'
    required: false
    default: 'github-actions[bot]'
  commit_message:
    description: 'Commit message, followed by version'
    required: false
    default: 'ci: updated package version'

runs:
  using: node20
  main: dist/index.js
