name: Test Publish

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Update Package Version
        uses: ./
        with:
          release_tag: ${{ github.event.release.tag_name }}
          target_branch: ${{ github.event.release.target_commitish }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Release When Failed
        if: failure()
        run:
          gh release delete ${{ github.event.release.tag_name }} --cleanup-tag
          --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
